apiVersion: v1
kind: ConfigMap
metadata:
 name: obedhipolito-configmap
 labels:
   app: postgres
data:
 DEV_SECRET_KEY: {DEV_SECRET_KEY}
 DEV_DATABASE: {DEV_DATABASE}
 DEV_USER: {DEV_USER}
 DEV_PASSWORD: {DEV_PASSWORD}
 DEV_HOST: {DEV_HOST}
 DEV_PORT: {DEV_PORT}
 
 PROD_SECRET_KEY: db-obed
 PROD_DATABASE: dtjfhtal
 PROD_USER: dtjfhtal
 PROD_PASSWORD: sWhEF6hsNSBJUEw1OFLpzEMDV4nke5zb
 PROD_HOST: isilo.db.elephantsql.com 
 PROD_PORT: "5432"
