apiVersion: apps/v1
kind: Deployment
metadata:
  name: obedhipolito
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obedhipolito
  template:
    metadata:
      labels:
        app: obedhipolito
    spec:
      containers:
      - image: okteto.dev/obedhipolito:latest
        name: obedhipolito
        envFrom:
        - configMapRef:
            name: obedhipolito-configmap
        livenessProbe:
          httpGet:
            path: /ht/
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: obedhipolito
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "obedhipolito"
    port: 8080
  selector:
    app: obedhipolito