# Generated by Django 3.1.3 on 2023-02-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(default='')),
                ('temporadas', models.IntegerField(default=0)),
                ('capitulos', models.IntegerField(default=0)),
                ('duracion', models.IntegerField(default=0)),
                ('clasificacion', models.TextField(default='')),
                ('categoria', models.TextField(default='')),
                ('idioma', models.TextField(default='')),
                ('plataforma', models.TextField(default='')),
                ('director', models.TextField(default='')),
                ('protagonista', models.TextField(default='')),
            ],
        ),
    ]
