# Generated by Django 3.1.3 on 2023-05-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='resena',
            field=models.TextField(default=''),
        ),
    ]
